### ISSUE TITLE
Use defer in script tags rather than putting them at the bottom of body?

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-template#16]
So this
```html
<head>
  <script src="example.js" defer></script>
</head>
```
rather than
```html
<body>
  <script src="example.js"></script>
</body>
```

**Comment by jrhorn424** [comment]
I really, really don't like putting scripts in the head. I'm sure I'm missing something important about it, but we should probably talk in person.

**Comment by jrhorn424** [comment]
Looks ok from a usability perspective. http://caniuse.com/#search=defer

**Comment by gaand** [comment]
@jrhorn424: So, is that yes, put it in head with defer? :-).

**Comment by jrhorn424** [comment]
Maybe. I just tried head with defer and the live-reload script barfed. Without defer it worked. I have no idea why that would be, but socket requests might be why.

**Comment by jrhorn424** [comment]
Possibly related #23

**Comment by jrhorn424** [comment]
Working as of c2886c7432a688c440296a9a30328ec08440c0c9, possibly earlier. Can we close this @gaand?

**Comment by gaand** [comment]
Yes.  Thanks.
